name: DelayedCommand
version: 0.1 Beta
author: Bjorno43
main: netherlands.bjorn.delayedcommand.Main
commands:
  dcmd:
    description: Perform a command after x amount of seconds
    usage: Syntax error! Try /dcmd seconds command Eg /dcmd 10 time set day
    permission: delayedcommand.dcmd
permissions:
   delayedcommand.*:
     description: Allowes access to all DelayedCommand commands
     children:
       delayedcommand.dcmd: op
     delayedcommand.dcmd:
       description: Makes the server perform a command after x amount of seconds
       default: op